version: 2.1

orbs:
  node: circleci/node@4.0.0

# Define the jobs we want to run for this project
jobs:
  update:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init

# Orchestrate our job run sequence
workflows:
  build_test:
    jobs:
      - update
      - node/test:
          requires:
            - update
