version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: circleci/node4.0.0
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
  test:
    docker:
      - image: circleci/node4.0.0
    steps:
      - run: npm test

# Orchestrate our job run sequence
workflows:
  build_test:
    jobs:
      - build
      - test:
          requires:
            - build