version: 2.1

orbs:
  node: circleci/node4.0.0

jobs:
  build:
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
  test:
    steps:
      - node/test


workflows:
  build_test:
    jobs:
      - build
      - test:
        requires:
          - build
